version: '3.1'

services:
  client:
    build: ./client/.
    ports:
      - "3000:3000"
    expose:
      - 3000
    depends_on:
      - server

  server:
    build: ./server/.
    ports:
      - "8080:8080"
    expose:
      - 8080
